host: "http://kong.poros-platform.10.74.166.198.nip.io"
username: "13925210746"
password: "ABC_abc1"
logger:
  name: py36
  logger_level: "DEBUG"
  stream_handler_level: "DEBUG"
  file: "py36.log"
  file_handler_level: "DEBUG"